# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sexual',
            fields=[
                ('sId', models.AutoField(primary_key=True, serialize=False, verbose_name='性别ID')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
            ],
        ),
        migrations.AddField(
            model_name='patients',
            name='pGender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.sexual', verbose_name='用户性别'),
        ),
    ]
