# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-26 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pGender',
            fields=[
                ('sId', models.AutoField(primary_key=True, serialize=False, verbose_name='性别ID')),
                ('gender', models.CharField(default='', max_length=10, null=True, verbose_name='性别')),
            ],
        ),
    ]
