# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-13 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200313_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='evaluate',
        ),
        migrations.AddField(
            model_name='comment',
            name='registration',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.registration', verbose_name='预约'),
        ),
    ]
