# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-26 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_pgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='pGender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.pGender', verbose_name='用户性别'),
        ),
    ]
