# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-28 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patients_pgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='charge',
            field=models.IntegerField(default=12, verbose_name='挂号费用'),
        ),
        migrations.AddField(
            model_name='registration',
            name='regState',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contretetime_a',
            name='a_10_00',
            field=models.BooleanField(default=True, verbose_name='10:00'),
        ),
        migrations.AlterField(
            model_name='contretetime_a',
            name='a_10_30',
            field=models.BooleanField(default=True, verbose_name='10:30'),
        ),
        migrations.AlterField(
            model_name='contretetime_a',
            name='a_11_00',
            field=models.BooleanField(default=True, verbose_name='11:00'),
        ),
        migrations.AlterField(
            model_name='contretetime_a',
            name='a_11_30',
            field=models.BooleanField(default=True, verbose_name='11:30'),
        ),
        migrations.AlterField(
            model_name='contretetime_a',
            name='a_8_00',
            field=models.BooleanField(default=True, verbose_name='8:00'),
        ),
        migrations.AlterField(
            model_name='contretetime_a',
            name='a_8_30',
            field=models.BooleanField(default=True, verbose_name='8:30'),
        ),
        migrations.AlterField(
            model_name='contretetime_a',
            name='a_9_00',
            field=models.BooleanField(default=True, verbose_name='9:00'),
        ),
        migrations.AlterField(
            model_name='contretetime_a',
            name='a_9_30',
            field=models.BooleanField(default=True, verbose_name='9:30'),
        ),
        migrations.AlterField(
            model_name='contretetime_a',
            name='scheduling_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.scheduling', verbose_name='排班ID'),
        ),
        migrations.AlterField(
            model_name='contretetime_p',
            name='p_13_30',
            field=models.BooleanField(default=True, verbose_name='13:30'),
        ),
        migrations.AlterField(
            model_name='contretetime_p',
            name='p_14_00',
            field=models.BooleanField(default=True, verbose_name='14:00'),
        ),
        migrations.AlterField(
            model_name='contretetime_p',
            name='p_14_30',
            field=models.BooleanField(default=True, verbose_name='14:30'),
        ),
        migrations.AlterField(
            model_name='contretetime_p',
            name='p_15_00',
            field=models.BooleanField(default=True, verbose_name='15:00'),
        ),
        migrations.AlterField(
            model_name='contretetime_p',
            name='p_15_30',
            field=models.BooleanField(default=True, verbose_name='15:30'),
        ),
        migrations.AlterField(
            model_name='contretetime_p',
            name='p_16_00',
            field=models.BooleanField(default=True, verbose_name='16:00'),
        ),
        migrations.AlterField(
            model_name='contretetime_p',
            name='p_16_30',
            field=models.BooleanField(default=True, verbose_name='16:30'),
        ),
        migrations.AlterField(
            model_name='contretetime_p',
            name='scheduling_p',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.scheduling', verbose_name='排班ID'),
        ),
    ]
