# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-29 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200228_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='visitState',
            field=models.BooleanField(default=False, verbose_name='就诊状态'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='regState',
            field=models.BooleanField(default=True, verbose_name='预约状态'),
        ),
    ]
